image: ruby:latest

stages:
- test

default:
  before_script:
    - apt-get update
    - apt-get install -y nodejs npm
    - npm ci

pa11y-tests:
  stage: test
  script:
    - npm run start-detached
    - npm run pa11y-ci:sitemap
