image: ruby:2

stages:
- test

default:
  before_script:
    - apt-get update
    - apt-get install -y nodejs npm
    - npm ci
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm/

pa11y-tests:
  stage: test
  script:
    - npm run start-detached
    - npm run pa11y-ci:sitemap
