stages:
- build
- test

install-dependencies:
  image: node:latest
  stage: build
  script:
    - npm ci

pa11y-tests:
  stage: test
  script:
    - npm run start-detached
    - npm run pa11y-ci:sitemap
