name: Backlog new issues

on:
  issues:
    types:
      - reopened
      - opened

jobs:
  triage_issues:
    if: github.repository == 'CivicActions/accessibility'
    runs-on: ubuntu-latest

    steps:
      - name: Backlog to project board
        uses: rachmari/actions-add-new-issue-to-column@1a459ef92308ba7c9c9dc2fcdd72f232495574a9
        with:
          action-token: ${{ secrets.GITHUB_TOKEN }}
          project-url: 'https://github.com/CivicActions/accessibility/projects/1'
          column-name: 'Backlog'
