name: Backlog new issues

on:
  issues:
    types:
      - reopened
      - opened

jobs:
  triage_issues:
    if: github.repository == 'CivicActions/accessibility'
    runs-on: ubuntu-latest

    steps:
      - name: Backlog to project board
        uses: actions/add-to-project@v1.0.2
        with:
          github-token: ${{ secrets.ADD_TO_CA_A11Y_PROJECT_PAT }}
          project-url: https://github.com/orgs/CivicActions/projects/5
