name: Checking links
permissions:
  contents: read

on:
  # Automatic check weekly
  schedule:
    - cron: "0 9 * * 1"
  pull_request:

jobs:
  build:
    name: Building site and running HTML proofer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source.
        uses: actions/checkout@v4

      - name: Install jekyll site dependencies.
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true

      - name: Build site
        run: npm run build

      - name: Run HTML proofer.
        run: npm run link-checker
