name: Checking links

on:
  # Automatic check weekly
  schedule:
    - cron: "0 9 * * 1"
  pull_request:

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          config-file: "markdown.links.config.json"
          use-quiet-mode: "yes"
          use-verbose-mode: "yes"
