name: pa11y tests

on: [push, workflow_dispatch]

jobs:
  build:
    name: Build and test.
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source.
        uses: actions/checkout@v2

      - name: Install jekyll site dependencies.
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true

      - name: Install pa11y-ci dependencies.
        run: npm install

      - name: Start up jekyll server.
        run: npm run start-detached

      - name: Run pa11y-ci.
        run: npm run pa11y-ci:sitemap

      - name: Display failure instructions.
        if: ${{ failure() }}
        run: |
          echo "::group::pa11y errors"
          echo "pa11y-ci found some accessibility problems, download 'pa11y_report' under artifacts to see the report."
          echo "::endgroup::"

      - name: Generate pa11y HTML report.
        if: ${{ always() }}
        run: npm run pa11y-ci:output

      - name: Save pa11y HTML report.
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: pa11y_report
          path: pa11y_report
